# -*- coding: utf-8 -GPK*-

{
    'name': 'Surya Sarpam',
    'version': '1.0',
    "author": 'Yali Technologies',
    "website": 'http://www.yalitechnologies.com/',
    'category': 'Hospital',
    'sequence': 15,
    'summary': 'Hospital Management',
    'description': 'Hospital Management',
    'depends': ['base', 'mail'],
    'data': [
        'data/access_rights.xml',
        'menu/main_menu.xml',
        'menu/employee_menu.xml',
        'menu/other_menu.xml',
        'menu/time_management.xml',
        # 'views/hr_employee.xml',
        # 'menu/product_menu.xml',
        'views/year.xml',
        'views/month.xml',
        'views/week.xml',        
        'views/day.xml',
        'views/employee/hr_employee.xml',
        'views/employee/hr_attachment.xml',
        'views/employee/hr_contact.xml',
        'views/employee/hr_department.xml',
        'views/employee/hr_employee.xml',
        'views/employee/hr_employee_category.xml',
        'views/employee/hr_employee_designation.xml',
        'views/employee/hr_experience.xml',
        'views/employee/hr_leave.xml',
        'views/employee/hr_leave_detail.xml',
        'views/employee/hr_qualification.xml',
        'views/employee/res_language.xml',
        'views/employee/res_religion.xml',
        'views/time_management/shift.xml',
    ],
    'demo': [

    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
